In [1]:
import numpy as np

# 10 students, 4 subjects: Math, Science, English, Programming
scores = np.array([
    [78, 85, 90, 88],
    [65, 70, 60, 75],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [70, 72, 68, 74],
    [88, 90, 85, 92],
    [45, 50, 55, 48],
    [82, 79, 84, 80],
    [95, 98, 92, 96],
    [60, 65, 63, 67]
])

subjects = ["Math", "Science", "English", "Programming"]

In [2]:
student_averages = scores.mean(axis=1)
print("Student averages:", student_averages)

Student averages: [85.25 67.5  91.5  58.75 71.   88.75 49.5  81.25 95.25 63.75]


In [3]:
subject_averages = scores.mean(axis=0)
for subject, avg in zip(subjects, subject_averages):
    print(f"{subject} class average: {avg:.2f}")

Math class average: 73.00
Science class average: 75.70
English class average: 75.00
Programming class average: 77.30


In [4]:
# Task 3: Overall highest and lowest single score in the whole dataset
print("Highest score:", scores.max())
print("Lowest score:", scores.min())

# Task 4: Which student has the best overall average
best_student_index = np.argmax(student_averages)
print(f"Best student: Student {best_student_index + 1} with average {student_averages[best_student_index]:.2f}")

# Task 5: Which subject has the highest class average
best_subject_index = np.argmax(subject_averages)
print(f"Best subject: {subjects[best_subject_index]} with average {subject_averages[best_subject_index]:.2f}")

Highest score: 98
Lowest score: 45
Best student: Student 9 with average 95.25
Best subject: Programming with average 77.30


In [5]:
# Task 6: How many students passed each subject (score >= 60)
passed_per_subject = (scores >= 60).sum(axis=0)
for subject, count in zip(subjects, passed_per_subject):
    print(f"{subject}: {count} students passed")

# Task 7: Standard deviation of scores per subject
std_per_subject = scores.std(axis=0)
for subject, std in zip(subjects, std_per_subject):
    print(f"{subject} standard deviation: {std:.2f}")

Math: 8 students passed
Science: 9 students passed
English: 8 students passed
Programming: 9 students passed
Math standard deviation: 15.89
Science standard deviation: 14.21
English standard deviation: 14.84
Programming standard deviation: 14.46


In [6]:
curved_scores = scores + 5
curved_scores = np.clip(curved_scores, 0, 100)
print(curved_scores)

[[ 83  90  95  93]
 [ 70  75  65  80]
 [ 97  93 100  96]
 [ 60  65  63  67]
 [ 75  77  73  79]
 [ 93  95  90  97]
 [ 50  55  60  53]
 [ 87  84  89  85]
 [100 100  97 100]
 [ 65  70  68  72]]


In [ ]:
# Summary of Findings:
# - Programming had the highest class average (77.30), while Math had the lowest (73.00)
# - Math also had the most inconsistent scores (highest standard deviation: 15.89)
# - Student 9 was the top performer overall, with a 95.25 average
# - Between 8-9 out of 10 students passed each subject
# - A 5-point curve was applied and capped at 100, benefiting students close to the maximum